**Pandas**

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(pd.__version__)
print(np.__version__)

2.2.2
2.0.2

In [ ]:
# creating List using Series
a=pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
a=pd.Series([1,2,3,4,5],
index=['a','b','c','d','e'])
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
student={
    "Name":"VISHNU",
    "department": "AIML"
}
S=pd.Series(student)
print(S)

Name          VISHNU
department      AIML
dtype: object

In [ ]:
m=pd.Series([20,30,40,50])
print(m)

0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
m+2

0    22
1    32
2    42
3    52
dtype: int64

In [ ]:
m/2

0    10.0
1    15.0
2    20.0
3    25.0
dtype: float64

In [ ]:
m-2

0    18
1    28
2    38
3    48
dtype: int64

In [ ]:
m%2

0    0
1    0
2    0
3    0
dtype: int64

In [ ]:
m.min()

20

In [ ]:
m.max()

50

In [ ]:
m.describe()

count     4.000000
mean     35.000000
std      12.909944
min      20.000000
25%      27.500000
50%      35.000000
75%      42.500000
max      50.000000
dtype: float64

In [ ]:
m.sum()

np.int64(140)

In [ ]:
m[m>15]

0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
name=pd.Series(["Vishnu","beja","HEllo"])
name.str.lower()

0    vishnu
1      beja
2     hello
dtype: object

In [ ]:
name.str.len()

0    6
1    4
2    5
dtype: int64

In [ ]:
name.str.upper()

0    VISHNU
1      BEJA
2     HELLO
dtype: object

In [ ]:
name.str.startswith("V")

0     True
1    False
2    False
dtype: bool

In [ ]:
name.str.endswith("a")

0    False
1     True
2    False
dtype: bool

**Data frame**

In [ ]:
student={
    "names":["Vishnu","Beja","Sathish","Manoj"],
    "age":[22,21,20,21],
    "department":["AIML","AIML","AIML","AIML"]
}
a=pd.DataFrame(student)
print(a)

     names  age department
0   Vishnu   22       AIML
1     Beja   21       AIML
2  Sathish   20       AIML
3    Manoj   21       AIML

In [ ]:
Rows=[(
    "Vishnu",22,"AIML"
),
(
    "Beja",21,"AIML"
),
(
    "Sathish",20,"AIML"
),
(
    "Manoj",21
)]
ds=pd.DataFrame(Rows)
print(ds)

         0   1     2
0   Vishnu  22  AIML
1     Beja  21  AIML
2  Sathish  20  AIML
3    Manoj  21  None

In [ ]:
#from numpy array
arr=np.random.rand(3,4)
c=pd.DataFrame(arr,columns=['A','B','C','D'],index=['a','b','c'])
print(c)

          A         B         C         D
a  0.777178  0.190777  0.761499  0.596397
b  0.166359  0.216652  0.237696  0.145737
c  0.010557  0.666688  0.817941  0.767423

In [ ]:
#Exploring Data Frames
data ={
    'Name':['Vishnu','Beja','Sathish','Manoj'],
    'Age':[22,21,20,21],
    'Score':['99','95','80','69'],
    'Grade':['A','A','A','B']
}
df=pd.DataFrame(data)
print(df)

      Name  Age Score Grade
0   Vishnu   22    99     A
1     Beja   21    95     A
2  Sathish   20    80     A
3    Manoj   21    69     B

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      object
 3   Grade   4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

             Age
count   4.000000
mean   21.000000
std     0.816497
min    20.000000
25%    20.750000
50%    21.000000
75%    21.250000
max    22.000000

In [ ]:
df.head()

      Name  Age Score Grade
0   Vishnu   22    99     A
1     Beja   21    95     A
2  Sathish   20    80     A
3    Manoj   21    69     B

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')

In [ ]:
df.dtypes

Name     object
Age       int64
Score    object
Grade    object
dtype: object

In [ ]:
df.nunique()

Name     4
Age      3
Score    4
Grade    2
dtype: int64

In [ ]:
df.isnull().sum()

Name     0
Age      0
Score    0
Grade    0
dtype: int64

In [ ]:
df.tail()

      Name  Age Score Grade
0   Vishnu   22    99     A
1     Beja   21    95     A
2  Sathish   20    80     A
3    Manoj   21    69     B

**Selecting ,Filtering Data**

In [ ]:
#Selecting Columns
df['Name'] #Single column
df.Name # or any 1 cmd

0     Vishnu
1       Beja
2    Sathish
3      Manoj
Name: Name, dtype: object

In [ ]:
#Multiple columns
df[['Name','Age']]

      Name  Age
0   Vishnu   22
1     Beja   21
2  Sathish   20
3    Manoj   21

**loc**

In [ ]:
df.loc[0]

Name     Vishnu
Age          22
Score        99
Grade         A
Name: 0, dtype: object

In [ ]:
df.loc[0:1]

     Name  Age Score Grade
0  Vishnu   22    99     A
1    Beja   21    95     A

In [ ]:
df.loc[0:2,'Name':'Score']

      Name  Age Score
0   Vishnu   22    99
1     Beja   21    95
2  Sathish   20    80

In [ ]:
df.iloc[0]

Name     Vishnu
Age          22
Score        99
Grade         A
Name: 0, dtype: object

In [ ]:
df.iloc[-1]

Name     Manoj
Age         21
Score       69
Grade        B
Name: 3, dtype: object

In [ ]:
df.iloc[0:2]

     Name  Age Score Grade
0  Vishnu   22    99     A
1    Beja   21    95     A

In [ ]:
df.iloc[0:2,0:2]

     Name  Age
0  Vishnu   22
1    Beja   21

In [ ]:
#Single Value
df.loc[0,'Name']

'Vishnu'

In [ ]:
df.iloc[0,0]

'Vishnu'

In [ ]:
df[(df['Score'] > 90) & (df['Grade'] =='A')]

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df[(df['Score'] > 90) | (df['Grade'] =='A')]

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df.query('Score > 90 and Age < 25')

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df.query('Grade =="A"')

      Name  Age Score Grade
0   Vishnu   22    99     A
1     Beja   21    95     A
2  Sathish   20    80     A

In [ ]:
df[df['Name'].isin(['Vishnu','Manoj'])]

     Name  Age Score Grade Example
0  Vishnu   22    99     A       a
3   Manoj   21    69     B       d

In [ ]:
df['Example']=['a','b','c','d']

In [ ]:
print(df)

      Name  Age Score Grade Example
0   Vishnu   22    99     A       a
1     Beja   21    95     A       b
2  Sathish   20    80     A       c
3    Manoj   21    69     B       d

In [ ]:
df['T|F']=df['Score']>=90

TypeError: '>=' not supported between instances of 'str' and 'int'

In [ ]:
print(df)

      Name  Age Score Grade Example
0   Vishnu   22    99     A       a
1     Beja   21    95     A       b
2  Sathish   20    80     A       c
3    Manoj   21    69     B       d

In [ ]:
df['Score']=df['Score'] + 5

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(df)

      Name  Age Score Grade Example
0   Vishnu   22    99     A       a
1     Beja   21    95     A       b
2  Sathish   20    80     A       c
3    Manoj   21    69     B       d

In [ ]:
def Grade(Score):
  if Score >=90:
    return 'A'
  elif Score >=80:
    return 'B'
  elif Score >=70:
    return 'C'
  elif Score >=60:
    return 'D'
  else:
    return 'F'
#apply() function
#adding new columns by using the logic or conditions
df['Grade_assigned'] = df['Score'].apply(Grade)
print(df)

TypeError: '>=' not supported between instances of 'str' and 'int'

In [ ]:
print(df)

      Name  Age Score Grade Example
0   Vishnu   22    99     A       a
1     Beja   21    95     A       b
2  Sathish   20    80     A       c
3    Manoj   21    69     B       d

In [ ]:
result={
    True:"Pass",
    False:"Fail"
}
Passs={'A':90,"B":80,"D":70}
df['pass']=df['T|F'].map(Passs)
print(df)

KeyError: 'T|F'

In [ ]:
df['result']=df['T|F'].map(result)
print(df)

KeyError: 'T|F'

In [ ]:
df.drop('pass',axis=1, inplace=True)
print(df)

KeyError: "['pass'] not found in axis"

In [ ]:
df.rename(columns={'result':'Result','Name':'Student'},inplace=True)
print(df)

   Student  Age Score Grade Example
0   Vishnu   22    99     A       a
1     Beja   21    95     A       b
2  Sathish   20    80     A       c
3    Manoj   21    69     B       d

In [ ]:
df.replace('b',np.nan,inplace=True)
print(df)

   Student  Age Score Grade Example
0   Vishnu   22    99   NaN       a
1     Beja   21    95   NaN     NaN
2  Sathish   20    80   NaN       c
3    Manoj   21    69     B       d

In [ ]:
df.sort_values('Age',ascending=False)

   Student  Age Score Grade Example
0   Vishnu   22    99   NaN       a
1     Beja   21    95   NaN     NaN
3    Manoj   21    69     B       d
2  Sathish   20    80   NaN       c

In [ ]:
df.sort_values(['Grade','Score'],ascending=[True,False])

   Student  Age Score Grade Example
3    Manoj   21    69     B       d
0   Vishnu   22    99   NaN       a
1     Beja   21    95   NaN     NaN
2  Sathish   20    80   NaN       c

In [ ]:
df.sort_values(['Age','Score'],ascending=[True,False])

   Student  Age Score Grade Example
2  Sathish   20    80   NaN       c
1     Beja   21    95   NaN     NaN
3    Manoj   21    69     B       d
0   Vishnu   22    99   NaN       a

In [ ]:
df.sort_index(ascending=False)

   Student  Age Score Grade Example
3    Manoj   21    69     B       d
2  Sathish   20    80   NaN       c
1     Beja   21    95   NaN     NaN
0   Vishnu   22    99   NaN       a

In [ ]:
df.nlargest(4 , 'Age')

   Student  Age Score Grade Example
0   Vishnu   22    99   NaN       a
1     Beja   21    95   NaN     NaN
3    Manoj   21    69     B       d
2  Sathish   20    80   NaN       c

In [ ]:
df.nsmallest(2,'Age')

   Student  Age Score Grade Example
2  Sathish   20    80   NaN       c
1     Beja   21    95   NaN     NaN

In [ ]:
data={
    'company':['HR','IT','HR','IT','HR'],
    'salaries':[70000,50000,55000,]
}
print(data)

{'company': ['HR', 'IT', 'HR', 'IT', 'HR'], 'salaries': [70000, 50000, 55000]}

In [ ]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'dept_id': [10, 20, 10, 30]
})

departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['Engineering', 'HR']
})